version: '3.8'
  
services:
    app:
        build: .
        ports:
            - "8080:8080"
        depends_on:
            - db
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/fakestore?createDatabaseIfNotExist=true&autoReconnect=true
            SPRING_DATASOURCE_USERNAME: Hoang
            SPRING_DATASOURCE_PASSWORD: Hoangdeptry_05
        entrypoint: ["sh", "-c", "sleep 5 && java -jar app.jar"]
  
    db:
        image: mysql:8.0.40
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: fakestore
            MYSQL_USER: Hoang
            MYSQL_PASSWORD: Hoangdeptry_05
        volumes:
            - db_data:/var/lib/mysql
            - ./fakestore.sql:/docker-entrypoint-initdb.d/fakestore.sql
    
volumes:
    db_data: